### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by Serfenia** [vraa/route-planner#1]
Hey, here's a list of improvements I would suggest:
- Change `wayPoints.map` to `wayPoints.each`. You don't use the purpose of `map` at all, you are just looping through it really (Dashboard.js).
- Create a generic function for the list items in your Dashboard component that you can re-use.
  Something like: 

```
function(property, value) {
    return (<li className={property}>
      <p className='value'>{value}</p>
      <p className='unit'>{property}</p>
    </li>)
  },
```
- Rename event handlers 
  Rename the event handlers (not the name, the function name of the listener) from 'on' (like onClick, onBlur) to 'handle' (handleClick, handleBlur). If you check the react website you see in the examples that this is naming convention is used by default

When I have more time I will look through it more.
Regards, Patrick

**Comment by vraa** [comment]
thanks for the suggestions, Serfenia. Agree with the map/each. 

Will be fixing it in next release.
