### ISSUE TITLE
Running grunt gives errors and never builds

### ISSUE THREAD

**Issue by guitarbeard** [vraa/route-planner#2]
I did `npm install` then ran `grunt` but I can't get it to build. I haven't modified the code at all, I only forked it. Not sure what I'm doing wrong. Great little app by the way! 
![screen shot 2015-11-20 at 6 48 23 pm](https://cloud.githubusercontent.com/assets/2850694/11316301/cf841ad6-8fb7-11e5-9260-3a632fc66187.png)

**Comment by vraa** [comment]
Fixed. Please verify now.
